#!/usr/bin/env python3
"""Vendor the provider catalog into ``aiden/providers/data``.

Two sources:

1. **pi's generated catalog** (``pi-ai/dist/providers/data/*.json``) — 41 providers.
2. **the Command Code extension's generated catalog** — pi has no built-in entry, so we
   derive ``commandcode.json`` from ``pi-commandcode-provider``'s generated TypeScript
   (input modalities, reasoning flags, selectable efforts), which is far more accurate than
   a hand-maintained list.

Source order for (1): ``--source DIR`` → ``PI_AI_DATA_DIR`` → auto-discovered global install.
Fallbacks for (2): ``COMMANDCODE_CATALOG_TS`` → auto-discovered extension → cached
``~/.pi/agent/commandcode-models.json`` → a minimal built-in list.

Usage:
    python scripts/sync_catalog.py                 # auto-discover everything
    python scripts/sync_catalog.py --source DIR    # explicit pi-ai data dir
    python scripts/sync_catalog.py --check         # report drift, write nothing
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TARGET = REPO / "aiden" / "providers" / "data"

COMMANDCODE_API_BASE = "https://api.commandcode.ai/provider/v1"
# anthropic-messages posts to {base}/v1/messages, so the base must not end in /v1.
COMMANDCODE_ANTHROPIC_BASE = "https://api.commandcode.ai/provider"

# Our thinking levels → Command Code's reasoning efforts.
THINKING_LEVELS = ("off", "minimal", "low", "medium", "high", "xhigh", "max")

FALLBACK_COMMANDCODE_MODELS = [
    "claude-sonnet-5",
    "claude-sonnet-4-6",
    "claude-haiku-4-5-20251001",
    "gpt-5.6-luna",
    "deepseek/deepseek-v4-pro",
    "meta/muse-spark-1.3-contributor",
]


# --------------------------------------------------------------------------- discovery


def discover_pi_data() -> Path | None:
    env = os.environ.get("PI_AI_DATA_DIR")
    if env and Path(env).is_dir():
        return Path(env)
    roots = (
        Path.home() / ".nvm" / "versions" / "node",
        Path("/usr/local/lib/node_modules"),
        Path("/opt/homebrew/lib/node_modules"),
    )
    for root in roots:
        if not root.exists():
            continue
        for data in root.glob("**/@earendil-works/pi-ai/dist/providers/data"):
            if data.is_dir():
                return data
    return None


def discover_commandcode_ts() -> Path | None:
    env = os.environ.get("COMMANDCODE_CATALOG_TS")
    if env and Path(env).is_file():
        return Path(env)
    roots = (Path.home() / ".pi" / "agent" / "npm" / "node_modules",)
    for root in roots:
        candidate = root / "pi-commandcode-provider" / "src" / "commandcode-catalog.ts"
        if candidate.is_file():
            return candidate
    return None


def discover_commandcode_cache() -> Path | None:
    candidate = Path.home() / ".pi" / "agent" / "commandcode-models.json"
    return candidate if candidate.is_file() else None


# --------------------------------------------------------------------------- parsing


def _parse_ts_record(src: str, name: str) -> dict:
    """Extract a flat ``{ "key": "str" | [...] | true | 12 }`` constant from TS source.

    The upstream file is generated by a sync script, so its shape is stable; a regex read
    avoids taking a TypeScript toolchain as a dependency.
    """
    match = re.search(rf"(?:export )?const {name}[^=]*=\s*\{{(.*?)\n\}}", src, re.S)
    if not match:
        return {}
    out: dict = {}
    for entry in re.finditer(
        r'"([^"]+)":\s*("(?:[^"\\]|\\.)*"|\[[^\]]*\]|true|false|\d+)', match.group(1)
    ):
        key, raw = entry.group(1), entry.group(2)
        if raw.startswith("["):
            out[key] = [v.strip().strip('"') for v in raw[1:-1].split(",") if v.strip()]
        elif raw in ("true", "false"):
            out[key] = raw == "true"
        elif raw.startswith('"'):
            out[key] = json.loads(raw)
        else:
            out[key] = int(raw)
    return out


def _thinking_level_map(efforts: list[str]) -> dict[str, str | None]:
    """Map our levels onto the model's published efforts (``None`` = unsupported)."""
    if not efforts:
        return {}
    out: dict[str, str | None] = {}
    for level in THINKING_LEVELS:
        out[level] = level if level in efforts else None
    # If the model lacks an explicit "off" effort, it still needs a suppressible entry.
    return out


def build_commandcode() -> tuple[dict, str]:
    """Return (catalog, provenance_note)."""
    ts_path = discover_commandcode_ts()
    anthropic: dict[str, dict] = {}
    completions: dict[str, dict] = {}
    note = "built-in fallback list"

    if ts_path:
        src = ts_path.read_text()
        modalities = _parse_ts_record(src, "MODEL_INPUT_MODALITIES")
        reasoning = _parse_ts_record(src, "MODEL_REASONING")
        efforts = _parse_ts_record(src, "MODEL_EFFORTS")
        max_out = _parse_ts_record(src, "MODEL_MAX_OUTPUT_TOKENS")
        model_ids = sorted(set(modalities) | set(reasoning) | set(efforts))
        for model_id in model_ids:
            _add_commandcode_model(
                model_id,
                anthropic,
                completions,
                input_modalities=modalities.get(model_id) or ["text"],
                is_reasoning=bool(reasoning.get(model_id, False)),
                efforts=list(efforts.get(model_id) or []),
                max_tokens=int(max_out.get(model_id) or 65_536),
            )
        note = f"parsed {len(model_ids)} models from {ts_path}"
    else:
        cache = discover_commandcode_cache()
        cached = {}
        if cache:
            try:
                cached = {m["id"]: m for m in json.loads(cache.read_text()).get("models", [])}
            except Exception:
                cached = {}
        model_ids = sorted(cached) or FALLBACK_COMMANDCODE_MODELS
        for model_id in model_ids:
            entry = cached.get(model_id, {})
            _add_commandcode_model(
                model_id,
                anthropic,
                completions,
                input_modalities=entry.get("input") or ["text"],
                is_reasoning=bool(entry.get("reasoning", True)),
                efforts=[],
                max_tokens=int(entry.get("maxTokens") or 65_536),
                context_window=int(entry.get("contextWindow") or 1_000_000),
            )
        note = f"cache {cache}" if cached else "built-in fallback list"

    return {"anthropic-messages": anthropic, "openai-completions": completions}, note


def _add_commandcode_model(
    model_id: str,
    anthropic: dict,
    completions: dict,
    *,
    input_modalities: list[str],
    is_reasoning: bool,
    efforts: list[str],
    max_tokens: int,
    context_window: int = 1_000_000,
) -> None:
    is_claude = model_id.startswith("claude-")
    base = {
        "id": model_id,
        "name": f"{model_id} (Command Code)",
        "api": "anthropic-messages" if is_claude else "openai-completions",
        "provider": "commandcode",
        "baseUrl": COMMANDCODE_ANTHROPIC_BASE if is_claude else COMMANDCODE_API_BASE,
        "reasoning": is_reasoning,
        "input": input_modalities or ["text"],
        "contextWindow": context_window,
        "maxTokens": max_tokens,
    }
    if not is_claude:
        # The Provider API's OpenAI-compatible surface rejects developer role/store.
        base["compat"] = {
            "supportsStore": False,
            "supportsDeveloperRole": False,
            "maxTokensField": "max_tokens",
        }
    level_map = _thinking_level_map(efforts)
    if level_map and is_reasoning:
        base["thinkingLevelMap"] = level_map
    (anthropic if is_claude else completions)[model_id] = base


# --------------------------------------------------------------------------- main


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", type=Path, default=None)
    ap.add_argument("--check", action="store_true", help="report drift without writing")
    args = ap.parse_args()

    source = args.source or discover_pi_data()
    TARGET.mkdir(parents=True, exist_ok=True)

    drift: list[str] = []
    vendored = 0

    if source:
        files = sorted(p for p in source.glob("*.json") if not p.name.startswith("."))
        for path in files:
            dest = TARGET / path.name
            if args.check:
                if not dest.exists() or dest.read_bytes() != path.read_bytes():
                    drift.append(path.name)
            else:
                shutil.copyfile(path, dest)
            vendored += 1
        print(f"pi-ai source: {source} ({len(files)} files)")
    else:
        print("pi-ai source: none found; keeping existing files")

    commandcode, note = build_commandcode()
    cc_payload = json.dumps(commandcode, indent=2, sort_keys=True)
    cc_path = TARGET / "commandcode.json"
    if args.check:
        if not cc_path.exists() or cc_path.read_text() != cc_payload:
            drift.append("commandcode.json")
    else:
        cc_path.write_text(cc_payload)
    print(
        f"commandcode: {note} "
        f"({len(commandcode['anthropic-messages'])} anthropic + "
        f"{len(commandcode['openai-completions'])} completions)"
    )

    if args.check:
        for name in drift:
            print(f"drift: {name}")
        return 1 if drift else 0

    manifest = {
        "generatedAt": datetime.now(UTC).isoformat(),
        "source": str(source) if source else "existing",
        "generator": "scripts/sync_catalog.py",
        "note": "pi-ai generated catalog vendored verbatim; commandcode derived locally.",
        "commandcode": {
            "apiBase": COMMANDCODE_API_BASE,
            "anthropicBase": COMMANDCODE_ANTHROPIC_BASE,
            "provenance": note,
            "rule": "claude-* use anthropic-messages, all others openai-completions",
        },
    }
    (TARGET / ".manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"wrote {vendored} vendored files + commandcode.json -> {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
